### ISSUE TITLE
After upgrade from 1.5 to 1.20, leveldb failed to load old data

### ISSUE THREAD

**Issue by lzy-lyf** [google/leveldb#469] opened 2017-05-17 08:53 UTC
I upgraded leveldb from 1.5 to 1.20 and tried to load old data which is stored by the 1.5 version, but failed. Log  reported:
2017/05/17-16:25:36.272084 41afa940 Recovering log #27134
2017/05/17-16:25:36.488518 41afa940 Level-0 table #27183: started
2017/05/17-16:25:37.409295 41afa940 Level-0 table #27183: 13953 bytes Corruption: bad block contents
I doubted if the data is truly corrupted, so I use 1.5 version and load again, this time all worked fine.
Can anyone tell me is there any extra work shall be done to old data before upgrade leveldb?

**Comment by ghemawat** [comment] 2017-05-17 14:39
On Wed, May 17, 2017 at 1:53 AM, lzy-lyf <notifications@github.com> wrote:

> I upgraded leveldb from 1.5 to 1.20 and tried to load old data which is
> stored by the 1.5 version, but failed. Log reported:
> 2017/05/17-16:25:36.272084 41afa940 Recovering log #27134
> 2017/05/17-16:25:36.488518 41afa940 Level-0 table #27183: started
> 2017/05/17-16:25:37.409295 41afa940 Level-0 table #27183: 13953 bytes
> Corruption: bad block contents
> I doubted if the data is truly corrupted, so I use 1.5 version and load
> again, this time all worked fine.
> Can anyone tell me is there any extra work shall be done to old data
> before upgrade leveldb?
>

There shouldn't be any need for extra work.

There isn't enough information here to diagnose the problem you are running
into however.  if your database is not too big and does not have any
private/sensitive information and you can upload it somewhere to others to
experiment with, that might be helpful.

Also, can you try the following:
(a) Make a copy of the database directory and operate on that to avoid any
problems caused by the experiments below.
(b) Using 1.5, open the database and call CompactRange(nullptr, nullptr) on
it.
(c) Close the database
(d) Use 1.20 and attempt to open the compacted database.

**Comment by cmumford** [comment] 2017-10-23 15:55
I know it's been a while since this was opened, but if paranoid_checks are being specified during open then 1.18 introduced a change that does further corruption checking of the index/meta/filter blocks.

It's been a while without feedback on this bug so I'm going to close it. If any additional information can be provided please reopen this issue.

**Closed by cmumford** 2017-10-23 15:55 UTC
