### ISSUE TITLE
memory runs out

### ISSUE THREAD

**Issue by FreemanFeng** [google/leveldb#271] opened 2014-12-12 01:26 UTC
Below is the core dump when I try to write 100m records into leveldb.

I found no way for leveldb to limit the usage of memory, it seems that leveldb will not stopping writting records into memory.

Program terminated with signal 6, Aborted.
#0  0x00c41410 in __kernel_vsyscall ()
(gdb) bt
#0  0x00c41410 in __kernel_vsyscall ()
#1  0x00496b10 in raise () from /lib/libc.so.6
#2  0x00498421 in abort () from /lib/libc.so.6
#3  0x00394fa0 in __gnu_cxx::__verbose_terminate_handler () at ../../.././libstdc++-v3/libsupc++/vterminate.cc:98
#4  0x00392845 in __cxxabiv1::__terminate (handler=0x394e50 <__gnu_cxx::__verbose_terminate_handler()>) at ../../.././libstdc++-v3/libsupc++/eh_terminate.cc:43
#5  0x00392882 in std::terminate () at ../../.././libstdc++-v3/libsupc++/eh_terminate.cc:53
#6  0x003929aa in __cxxabiv1::__cxa_throw (obj=0xab501508, tinfo=0x3bf474, dest=0x392ee0 <std::bad_alloc::~bad_alloc()>) at ../../.././libstdc++-v3/libsupc++/eh_throw.cc:76
#7  0x00392fbe in operator new (sz=1048560) at ../../.././libstdc++-v3/libsupc++/new_op.cc:63
#8  0x0036cd01 in allocate (__n=<optimized out>, this=<optimized out>) at /home/nemo/gcc-4.2.0/i686-pc-linux-gnu/libstdc++-v3/include/ext/new_allocator.h:91
#9  std::string::_Rep::_S_create (__capacity=1048547, __old_capacity=24649, __alloc=...) at /home/nemo/gcc-4.2.0/i686-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:589
#10 0x0036d9f8 in std::string::_Rep::_M_clone (this=0x9c340010, __alloc=..., __res=0) at /home/nemo/gcc-4.2.0/i686-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:611
#11 0x0036e6a8 in std::string::reserve (this=0x95a31e4, __res=<optimized out>) at /home/nemo/gcc-4.2.0/i686-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:492
#12 0x0036e8e2 in std::string::append (this=0x95a31e4, __s=0x6b0d5e9b "1:0:65:65:65:U37227:R39", __n=23) at /home/nemo/gcc-4.2.0/i686-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:313
#13 0x006c2cd4 in leveldb::BlockBuilder::Add(leveldb::Slice const&, leveldb::Slice const&) () from /vobs/ucab/lib/libleveldb.so.1
#14 0x006c6e47 in leveldb::TableBuilder::Add(leveldb::Slice const&, leveldb::Slice const&) () from /vobs/ucab/lib/libleveldb.so.1
#15 0x0069942a in leveldb::BuildTable(std::string const&, leveldb::Env*, leveldb::Options const&, leveldb::TableCache*, leveldb::Iterator*, leveldb::FileMetaData*) () from /vobs/ucab/lib/libleveldb.so.1
#16 0x006a21b5 in leveldb::DBImpl::WriteLevel0Table(leveldb::MemTable*, leveldb::VersionEdit*, leveldb::Version*) () from /vobs/ucab/lib/libleveldb.so.1
#17 0x006a2fb5 in leveldb::DBImpl::CompactMemTable() () from /vobs/ucab/lib/libleveldb.so.1
#18 0x006a3d3c in leveldb::DBImpl::BackgroundCompaction() () from /vobs/ucab/lib/libleveldb.so.1
#19 0x006a4922 in leveldb::DBImpl::BackgroundCall() () from /vobs/ucab/lib/libleveldb.so.1
#20 0x006a495d in leveldb::DBImpl::BGWork(void*) () from /vobs/ucab/lib/libleveldb.so.1
#21 0x006cde3f in leveldb::(anonymous namespace)::PosixEnv::BGThreadWrapper(void*) () from /vobs/ucab/lib/libleveldb.so.1
#22 0x0026a912 in start_thread () from /lib/libpthread.so.0
#23 0x005434ae in clone () from /lib/libc.so.6

**Comment by cmumford** [comment] 2016-01-16 00:08
Duplicate of issue #96

**Closed by cmumford** 2016-01-16 00:08 UTC
Labels: bug, duplicate
