### ISSUE TITLE
Getting frequent error saying "Corruption: not an sstable (bad magic number)"

### ISSUE THREAD

**Issue by YuvarajPLDB** [google/leveldb#706] opened 2019-07-18 15:30 UTC
Hi,

We are using Level DB 1.8 version, we are frequently getting "Corruption: not an sstable (bad magic number". 
Facing difficult to find the root cause, could you please tell me on what scenarios this error may throw?

Thanks,
Yuvaraj P.

**Comment by tmm1** [comment] 2019-07-23 18:53
This usually indicates some sort of disk corruption. What operating system and filesystem are you using?

**Comment by cmumford** [comment] 2019-07-29 22:55
What @tmm1 said is correct. v1.8 is about five years old and at least one (d84c825a70a843bb107de8b732cb79e584cefd17) corruption bug has been fixed since then. I'm going to close this as answered, but If you can reproduce this crash on the current release (v1.22) please reopen and we will look into this error.

**Closed by cmumford** 2019-07-29 22:55 UTC
