### ISSUE TITLE
Db corruption observed with powerloss

### ISSUE THREAD

**Issue by apurvcohesity** [google/leveldb#333] opened 2016-01-20 18:14 UTC
I have the following db that we can open for reads but every attempt to write fails with:
Corruption: not an sstable (bad magic number)

I am not sure which ldb file is corrupt (there does appear to be 1 0 sized file. But then leveldb code doesn't write ldb files to .ldbtmp and does rename, so in power loss cases, it's possible to end up with 0 sized ldb files).

Can you shed some light as to which ldb file is corrupt and why is it covered by the manifest?

[670B3wI.aux.zip](https://github.com/google/leveldb/files/97866/670B3wI.aux.zip)

**Comment by cmumford** [comment] 2016-01-21 01:01
The corrupt file is 001195.ldb - and it's an empty file. It is true that leveldb does not flush/sync/rename *.ldb files when writing, but it does do that when writing the MANIFEST - and that's what references the *.ldb files. The manifest is written afterwards, so this should ensure that the *.ldb files are safely on disk before being referenced.

So, yes; this could be a bug. It could be a hardware failure. It could be interference by another program (like antivirus/malware). etc. etc.

Have you been able to reproduce this? What version of leveldb? What OS?

**Comment by cmumford** [comment] 2019-03-29 22:31
Closing due to lack of input or reproduction case.

**Closed by cmumford** 2019-03-29 22:31 UTC
Labels: bug
