### ISSUE TITLE
Possiblity of corruption in table_builder::WriteRawBlock()

### ISSUE THREAD

**Issue by nirendraa** [google/leveldb#628] opened 2018-10-03 04:15 UTC
Hi,

In method table_builder::WriteRawBlock():
1. block_content are written first
2. Trailer is calculated
3. Trailer is appended

With this, there is a possibility of corruption in case of a crash after step 1. 
We noticed few corruptions with this as a root cause in Android environment.
Is there a specific reason for writing in this order?

There seems to be two possible solutions for handling this:
1. Calculating the trailer before writing the content and doing two writes of Block_content and trailer one after another. This reduces the possibilty of corruption although doesn't fully eliminates it.
2. Doing a scatter-gather write of both block_content and trailer togather with an interface similar to writev().

**Comment by ghemawat** [comment] 2018-10-03 15:52
Whether one write() call is done or a single scatter-gather call (writev)
is done doesn't really affect crash resistance.  There is no atomicity
guarantee on even a single write call.  So whatever corruption you have
noticed won't be fixed by the suggested changes.

To see why even a single write call be non-atomic, consider the case where
the written data spans multiple disk blocks and the disk hardware operates
a block at a time.  Or the OS buffer cache writes different modified blocks
at different times.

**Comment by nirendraa** [comment] 2018-10-04 06:05
Hi Sanjay,

Thank you for your response.
Agreed that disk may not provide crash consistency for a write call although journaling file systems like ext4 will first log the operation in a journal before issuing actual disk write.
In case of a crash, journal will be replayed to ensure consistency. User will get success only after data is committed to a journal.

Coming back to the possibility of crash here, it can still be reduced by first calculating trailer before making two seperate writes for block_content and trailer.

Regards,
Nirendra

**Comment by pwnall** [comment] 2019-01-08 06:30
Sorry, I don't buy the argument around corruption recovery here. Assuming the right options (see `leveldb::WriteOptions::sync` and `leveldb::ReadOptions::verify_checksums`) and no media errors, you should not lose data or get corrupted data after a write operation succeeds.

There is a window of time between when a write operation is issued and when it succeeds, where a crash will cause data loss. This is expected in every database system, as writes aren't instant. Each system makes its trade-offs around throughput, latency and memory consumption, and these trade-offs impact the size of this window.

I claim that your proposed change is simply an instance of such a trade-off. Even if you have a transactional filesystem, there's still a window of time when the FS has to write the log entry to disk. If that write is interrupted by a crash, the data is lost. So, the change should be judged based on the criteria above. Coming to that, I'm skeptical that the memory churn is outweighed by the reduction in OS-level or libc-level bookkeeping, so I'll close this issue.

If you  have benchmark results to prove your point, and it's important, please comment on this issue. I'll see the comments even if the issue is closed. Thank you!

**Closed by pwnall** 2019-01-08 06:30 UTC

**Comment by flplv** [comment] 2020-06-17 18:40
as a 2c opinion: if one day you decide to add crash robustness to the database files, SQLite could be a good reference: https://www.sqlite.org/lockingv3.html#rollback
