### ISSUE TITLE
Doubt on LevelDB RAM management for large data

### ISSUE THREAD

**Issue by ruckard** [google/leveldb#866] opened 2020-12-26 11:11 UTC
We are using leveldb for storing about 3 million blocks which each of them are about 260 bytes in size.
Just looping over them LevelDB seems to use 800 MiB of RAM which seems too excesive for our needs.

I have written an small program that demonstrates the problem: [https://github.com/ruckard/LevelDB-memory-footprint](https://github.com/ruckard/LevelDB-memory-footprint) .

Anyways the C++ program boils down to:
```
    leveldb::DB* db;
    leveldb::Options options;
    options.create_if_missing = true;

    leveldb::Status status = leveldb::DB::Open(options, "./testdb", &db);
    leveldb::Iterator* it = db->NewIterator(leveldb::ReadOptions());
    
    for (it->SeekToFirst(); it->Valid(); it->Next())
    {
        // cout << it->key().ToString() << " : " << it->value().ToString() << endl;
    }
```

As you can see we don't even do anything with the read data. We just loop it.

Using ```fill_cache = true``` does not make any difference.

Is there anything that I'm missing?
Is it LevelDB designed to behave like that on purpose?
Is this a LevelDB bug?
Maybe is there a workaround to decrease the LevelDB RAM consumption when reading bulk of data?

Thank you very much!

Note: This has been tested against the leveldb 6721eda0b46654d3531b4a0a00c90dc659b337d6 commit (Your current master branch HEAD commit) on an Ubuntu 20.04 system.

**Comment by cmumford** [comment] 2020-12-28 19:18
Hi @ruckard . Thx for the question and writing the sample program.

The memory consumption you are seeing is because the POSIX Env, which is the default, maps the table files into memory.

https://github.com/google/leveldb/blob/6721eda0b46654d3531b4a0a00c90dc659b337d6/util/env_posix.cc#L528-L529

They are mapped into the virtual address space read-only/shared, and are backed by the file contents. So the OS will consume physical RAM for those file contents, but will release the RAM when it comes under memory pressure as the data is backed by the file. You can verify this by changing `g_mmap_limit` to zero, which will cause leveldb to fallback to opening/closing files when needed.

https://github.com/google/leveldb/blob/6721eda0b46654d3531b4a0a00c90dc659b337d6/util/env_posix.cc#L45-L49

If you don't want the mmap behavior then you can use your own Env.

**Comment by ruckard** [comment] 2020-12-28 20:21
I have tried to use ```EnvPosixTestHelper::SetReadOnlyMMapLimit()``` but it seemed to be private.

Modifying ```int g_mmap_limit = kDefaultMmapLimit;``` into ```int g_mmap_limit = 0;``` did the trick.

I also have more doubts like if the memory is actually used with 800 MiB for a few microseconds while reading the info from the file.

And, well, the most important is the drawbacks of this method.
I guess this is fine when you want to load data from this file/database in a bulk manner.

But maybe when you want to check later random data from this same file/database it will be much slower (and it will use more cpu) than the default mmap method?

Thank you.

**Comment by pwnall** [comment] 2020-12-31 00:52
I think that the best approach for your problem is to fork (copy + rename) `util/env_posix.cc` and tweak it to meet your needs. 

The considerations you mention above are entirely valid. There is no universally-optimal Env, and the "right" implementation depends entirely on your use case and performance needs. I'd tackle this problem by implementing a few alternatives and benchmarking the use case you care about.

**Closed by pwnall** 2020-12-31 00:52 UTC
Labels: question

**Comment by Krishna7557** [comment] 2021-09-06 04:55
@ruckard, we have also done same test by tuning the gmmap_limit to 0. For us when bulk read(may be around 10 million entries) happens(seq read), we could still Ram is increasing. How you confirmed that the issue is fixed

**Comment by lasiaqq** [comment] 2022-09-18 10:00
Hi, @Krishna7557 Did you find what is the cause for this?
